// Every feature registers itself here, one import line per stream, under its own anchor
// (field-ready §1.1 order). Imported by App before the first render.

// @HUB
// @HUB-UI
import "./hub-ui";
// @E-lib
// @E-srv
import "./e-srv";
// @J
import "./j";
// @A-engine
import "./a-engine";
// @A-notify
import "./a-notify";
// @D
import "./d";
// @K-animals
import "./k-animals";
// @K-files
import "./k-files";
// @I
import "./i";
// @B
import "./b";
// @G
import "./g";
// @P
import "./p";
// @Q
// @C
import "./c";
// @F
// @S
// @A3
// @H
// @L
// @M
// @Z
