//! Signals math parity with the kit's `calculations.py`. The fixture was
//! generated by running the kit's functions on these inputs.

use std::collections::BTreeMap;

use chrono::{DateTime, Utc};
use op_engine::calc;
use serde_json::{Map, Value};

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/kit_calculations.json")).unwrap()
}

fn t(s: &str) -> DateTime<Utc> {
    DateTime::parse_from_rfc3339(s).unwrap().with_timezone(&Utc)
}

/// Equal as JSON, with numbers compared by value (Python ints vs floats).
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => (x.as_f64().unwrap() - y.as_f64().unwrap()).abs() < 1e-9,
        (Value::Array(x), Value::Array(y)) => x.len() == y.len() && x.iter().zip(y).all(|(a, b)| same(a, b)),
        (Value::Object(x), Value::Object(y)) => x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w))),
        _ => a == b,
    }
}

macro_rules! check {
    ($got:expr, $want:expr, $case:expr) => {{
        let (g, w): (Value, Value) = ($got, $want.clone());
        assert!(same(&g, &w), "case {}\n got  {g}\n want {w}", $case);
    }};
}

#[test]
fn animal_units() {
    for c in fixture()["animal_units"].as_array().unwrap() {
        let got = calc::animal_units(c["species"].as_str().unwrap(), c["count"].as_i64().unwrap(), c["stated"].as_f64());
        check!(serde_json::json!(got), c["expected"], c);
    }
}

#[test]
fn grazing_pressure() {
    for c in fixture()["grazing_pressure"].as_array().unwrap() {
        let counts: BTreeMap<String, i64> = serde_json::from_value(c["counts"].clone()).unwrap();
        let areas: BTreeMap<String, Option<f64>> = serde_json::from_value(c["areas"].clone()).unwrap();
        let got = calc::grazing_pressure(&counts, c["herd_count"].as_i64().unwrap(), c["window_days"].as_f64().unwrap(), &areas);
        check!(Value::Object(got), c["expected"], c);
    }
}

#[test]
fn rest_days() {
    let c = &fixture()["rest_days"];
    let last: BTreeMap<String, Option<DateTime<Utc>>> = c["last"].as_object().unwrap().iter().map(|(k, v)| (k.clone(), v.as_str().map(t))).collect();
    let got = calc::rest_days(&last, t(c["as_of"].as_str().unwrap()));
    check!(serde_json::to_value(got).unwrap(), c["expected"], "rest_days");
}

#[test]
fn forage_estimate() {
    for c in fixture()["forage_estimate"].as_array().unwrap() {
        let got = calc::forage_estimate(c["ndvi_mean"].as_f64(), c["height_inches"].as_f64(), c["residual"].as_f64().unwrap());
        check!(got, c["expected"], c);
    }
}

#[test]
fn recovery_trend() {
    for c in fixture()["recovery_trend"].as_array().unwrap() {
        let hist: Vec<(DateTime<Utc>, f64)> = c["history"].as_array().unwrap().iter().map(|p| (t(p[0].as_str().unwrap()), p[1].as_f64().unwrap())).collect();
        check!(calc::recovery_trend(&hist), c["expected"], c);
    }
}

#[test]
fn feed_budget_days() {
    for c in fixture()["feed_budget_days"].as_array().unwrap() {
        let got = calc::feed_budget_days(
            c["available_kg_dm"].as_f64().unwrap(),
            c["herd_animal_units"].as_f64().unwrap(),
            calc::DEFAULT_INTAKE_KG_DM_PER_AU_DAY,
            calc::DEFAULT_UTILIZATION,
            c["daily_growth_kg_dm"].as_f64().unwrap(),
        );
        check!(serde_json::json!(got), c["expected"], c);
    }
}

#[test]
fn risk_flags() {
    for c in fixture()["risk_flags"].as_array().unwrap() {
        let sections: Map<String, Value> = c["sections"].as_object().unwrap().clone();
        check!(Value::Array(calc::risk_flags(&sections)), c["expected"], c);
    }
}

#[test]
fn behavior() {
    for c in fixture()["behavior"].as_array().unwrap() {
        let fixes: Vec<String> = serde_json::from_value(c["fix_collars"].clone()).unwrap();
        let cues: Vec<(String, Option<f64>)> = c["cues"].as_array().unwrap().iter().map(|p| (p[0].as_str().unwrap().to_owned(), p[1].as_f64())).collect();
        check!(calc::behavior(&fixes, &cues, c["window_days"].as_f64().unwrap()), c["expected"], c);
    }
}
